### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by kirstjn** [mondora/mondora-website-front#34]
As a guest user I want to read a plain text description of mondora, so I can view it at my own pace if I don't like the animated text.
# Acceptance
- Plain text, black with white background, at bottom of page
- Guest is interested and clicks on "about us" section next.

**Comment by kirstenjr87** [comment]
![dscn1118](https://cloud.githubusercontent.com/assets/10920516/6893499/cc870c6a-d6cd-11e4-8c39-8731c507a583.JPG)
