### ISSUE TITLE
Background header images and box images/colours

### ISSUE THREAD

**Issue by kirstjn** [mondora/mondora-website-front#39]
As a guest user I want to see some good quality images/colours in the header of each page and in the clickable boxes (links - see template) so that I can appreciate the website more and spend more time on it.

**Comment by kirstenjr87** [comment]
![dscn1121](https://cloud.githubusercontent.com/assets/10920516/6893449/5974ede6-d6cd-11e4-8fc8-8dfc32df3d5b.JPG)
